//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logger.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logger.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion is not possible exception.
        /// </summary>
        internal static string ConversionNotPossibleException {
            get {
                return ResourceManager.GetString("ConversionNotPossibleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string argument exception.
        /// </summary>
        internal static string EmptyStringArgumentException {
            get {
                return ResourceManager.GetString("EmptyStringArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help link:.
        /// </summary>
        internal static string ExceptionExtensions_DetailedException_HelpLink {
            get {
                return ResourceManager.GetString("ExceptionExtensions_DetailedException_HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- INNER EXCEPTION ---.
        /// </summary>
        internal static string ExceptionExtensions_DetailedException_InnerException {
            get {
                return ResourceManager.GetString("ExceptionExtensions_DetailedException_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string ExceptionExtensions_DetailedException_Message {
            get {
                return ResourceManager.GetString("ExceptionExtensions_DetailedException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string ExceptionExtensions_DetailedException_Source {
            get {
                return ResourceManager.GetString("ExceptionExtensions_DetailedException_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace:.
        /// </summary>
        internal static string ExceptionExtensions_DetailedException_StackTrace {
            get {
                return ResourceManager.GetString("ExceptionExtensions_DetailedException_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target site:.
        /// </summary>
        internal static string ExceptionExtensions_DetailedException_TargetSite {
            get {
                return ResourceManager.GetString("ExceptionExtensions_DetailedException_TargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string ExceptionExtensions_DetailedException_Type {
            get {
                return ResourceManager.GetString("ExceptionExtensions_DetailedException_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stream argument.
        /// </summary>
        internal static string InvalidStreamArgumentException {
            get {
                return ResourceManager.GetString("InvalidStreamArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add duplicate.
        /// </summary>
        internal static string KeyedCollectionWrapper_CannotAddDuplicate {
            get {
                return ResourceManager.GetString("KeyedCollectionWrapper_CannotAddDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not cloneable.
        /// </summary>
        internal static string ObjectExtensions_DeepCloning_ObjectNotCloneable {
            get {
                return ResourceManager.GetString("ObjectExtensions_DeepCloning_ObjectNotCloneable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is not absolute argument exception.
        /// </summary>
        internal static string PathNotAbsoluteArgumentException {
            get {
                return ResourceManager.GetString("PathNotAbsoluteArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not directory argument exception.
        /// </summary>
        internal static string PathNotDirectoryArgumentException {
            get {
                return ResourceManager.GetString("PathNotDirectoryArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path argument is not a file.
        /// </summary>
        internal static string PathNotFileArgumentException {
            get {
                return ResourceManager.GetString("PathNotFileArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not relative argument exception.
        /// </summary>
        internal static string PathNotRelativeArgumentException {
            get {
                return ResourceManager.GetString("PathNotRelativeArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        internal static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parse format for serialport.
        /// </summary>
        internal static string SerialPortInstance_InvalidParseFormat {
            get {
                return ResourceManager.GetString("SerialPortInstance_InvalidParseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream not readable argument exception.
        /// </summary>
        internal static string StreamNotReadableArgumentException {
            get {
                return ResourceManager.GetString("StreamNotReadableArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream not readable.
        /// </summary>
        internal static string StreamNotReadableException {
            get {
                return ResourceManager.GetString("StreamNotReadableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream not seekable argument exception.
        /// </summary>
        internal static string StreamNotSeekableArgumentException {
            get {
                return ResourceManager.GetString("StreamNotSeekableArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream not writeable argument exception.
        /// </summary>
        internal static string StreamNotWriteableArgumentException {
            get {
                return ResourceManager.GetString("StreamNotWriteableArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream not writeable.
        /// </summary>
        internal static string StreamNotWriteableException {
            get {
                return ResourceManager.GetString("StreamNotWriteableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching members found.
        /// </summary>
        internal static string TypeExtensions_NoMatchingMembers {
            get {
                return ResourceManager.GetString("TypeExtensions_NoMatchingMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type count mismatches parameter value count.
        /// </summary>
        internal static string TypeExtensions_ParameterTypeCountMismatchParameterValueCount {
            get {
                return ResourceManager.GetString("TypeExtensions_ParameterTypeCountMismatchParameterValueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many matching members found.
        /// </summary>
        internal static string TypeExtensions_TooManyMatchingMembers {
            get {
                return ResourceManager.GetString("TypeExtensions_TooManyMatchingMembers", resourceCulture);
            }
        }
    }
}
